### ISSUE TITLE
Support for 1.1. schema of mseedindex

### ISSUE THREAD

**Issue by markcwill** [iris-edu/portable-fdsnws-dataselect#27]
Hi, we're testing this out, and following the wiki, using the current version of `mseedindex` (2.7), it uses a "1.1" schema, which is incompatible with the current version of this code. 

I was able to check out the `v2.6` tag of `mseedindex`, build a new indexer, and re-index my test data set, and this solved the issue. Luckily it was just 1 day of data, and took ~5 min, but I'd be a little annoyed if I had indexed a lot of data and had to redo it. (Our next stage of eval testing will be ~6 months/5TB).

Are there roadmap plans to add support for 1.1, and is there any disadvantage to just using 1.0? Or any plans for a schema migration tool (probably out of the scope of this project)?

In the short term, it would also be useful to modify the wiki and suggest building/using `mseedindex` <=2.6 for this.

**Comment by chad-iris** [comment]
Thanks for the reminder @markcwill.  I'll get portable-fdsnws-dataselect updated to handle the 1.1 schema.  I'm pretty sure it's already compatible, just a new, currently unused, column so I _think_ we just need to update the schema check.

**Comment by chad-iris** [comment]
Fixed in v1.2.0 with commit 8fb57ec77581662271e81256b2fbd8f67dbf0c09.

New release uploaded to PyPI.

**Comment by markcwill** [comment]
Thanks @chad-iris!
